# Nombre del flujo de trabajo
name: Java CI con Gradle

# Se ejecuta en cada push a cualquier rama
on: [push]

jobs:
  build:
    # Se ejecuta en una máquina virtual con la última versión de Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura el JDK (Java Development Kit) a la versión 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Configura Gradle para optimizar el proceso de build
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 4. (CORRECCIÓN) Da permisos de ejecución al script gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 5. Ejecuta el comando de build de Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # 6. (Opcional) Sube el artefacto (.jar) para que puedas descargarlo
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LogMyBlockNeoForge-build
          path: build/libs/*.jar
