name: Build Mod

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define aquí las versiones de Minecraft para las que quieres construir tu mod
        minecraft_version: ['1.21', '1.21.1', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7'] 
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

        
    - name: Make gradlew executable
      run: chmod +x gradlew
        
        
    - name: Build with Gradle
      run: ./gradlew build -Pminecraft_version=${{ matrix.minecraft_version }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LogMyBlockNeoForge-${{ matrix.minecraft_version }}
        path: build/libs/
